name: "Local Xray SOCKS"
version: "0.1.9"
slug: "local_xray_socks"
description: "Xray client that exposes a local SOCKS5 proxy for Keenetic"
url: "https://github.com/firmfreez/ha-xray-socks-addon"
startup: services
boot: auto
init: false
arch:
  - aarch64

ports:
  1080/tcp: 1080

ports_description:
  1080/tcp: "SOCKS5 TCP port for Keenetic"

options:
  subscription_url: ""
  link: ""
  server: ""
  port: 443
  uuid: ""
  sni: ""
  flow: ""
  fingerprint: ""
  alpn: ""
  socks_port: 1080
  loglevel: "warning"

schema:
  subscription_url: "str?"
  link: "str?"
  server: "str?"
  port: port
  uuid: "str?"
  sni: "str?"
  flow: "str?"
  fingerprint: "str?"
  alpn: "str?"
  socks_port: port
  loglevel: list(none|error|warning|info|debug)?
